# Site settings
title: Checkmap
SEOTitle: Checkmap | 博客
header-img: img/post-bg-home.jpg
#email: xiangegg666@gmail.com
description: "Checkmap | 博客"
keyword: "Checkmap, 破威力, 黄油, Galgame, Anime, Review"
url: "http://pockies.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Let's Make Waifu Great Again！"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
#disqus_username: pockies

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: a0a163a5048b3508e3ec   #生成的clientID
  clientSecret: 48de0e9e67bbfe9f1c14ccba43f82f2a0b9c02fd  #同上
  repo: pockies.github.io    #仓库名称
  owner: Pockies    #github用户名
  admin: Pockies
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计
# Analytics settings



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Plum's Blog",
        href: "https://plumz.me/"
    },{
        title: "suzumiyashirone's Blog",
        href: "https://suzumiyashirone.github.io/"
    },{
        title: "螺莉莉数据中心",
        href: "https://roriri.one/"
    }
]
